spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        greetings-in:
          destination: greetings-in
          contentType: application/json
        greetings-out:
          destination: greetings-in
          contentType: application/json
          
kafkaTopic: greetings-poster
